### ISSUE TITLE
Oscillatory behavior of Zernikes

### ISSUE THREAD

**Issue by lindsayad** [lindsayad/jupyter_notebooks#1]
@aprilnovak @paulromano @BruceWyxv has anyone experienced oscillatory behavior when using higher order Zernike polynomials? Some cursory searches suggest that this is possible but I haven't found any great literature on it. I have this notebook [here](https://github.com/lindsayad/jupyter_notebooks/blob/master/oscillatory-zernikes.ipynb) that reads Zernike tally information from OpenMC output. The mesh tally looks like so:

![image](https://user-images.githubusercontent.com/10248304/40373877-195d9fd4-5da5-11e8-97e6-9fb0e4240cc9.png)

The Zernike fits for different even order Zernikes look like this:

![image](https://user-images.githubusercontent.com/10248304/40373918-30439a5a-5da5-11e8-94f1-465c0f54b980.png)

Going to higher orders just makes the oscillations worse.

![image](https://user-images.githubusercontent.com/10248304/40374092-939012aa-5da5-11e8-9ba3-29684a54353c.png)

I didn't know the best place to have a discussion/brain dump on this as it's not immediately obvious to me that it's an issue with anyone's code...

**Comment by lindsayad** [comment]
@BruceWyzv A valid concern. Thanks to your comment, I did realize that I wasn't doing the total normalization process correctly (generation + evaluation) since we've changed the normalization process in OpenMC: we now leave normalization entirely to the user, e.g. we use the "standard" normalization when generating coefficients in OpenMC.

I've updated the [notebook](https://github.com/lindsayad/jupyter_notebooks/blob/master/oscillatory-zernikes.ipynb) so that I use the "orthonormal" normalization when *evaluating* the series. Unfortunately, even with that fix, oscillations are still present. And I checked that the plots don't just represent individual harmonics. To be sure, I formed a series to represent an analytical cosinusoid. The series representation is shown below:

![image](https://user-images.githubusercontent.com/10248304/40376623-0005ca28-5dac-11e8-8801-5b8561b01196.png)

**Comment by BruceWyxv** [comment]
@lindsayad OK, I'm following now. Sorry, I hope my earlier comment didn't cause too much of a wild goose chase.

Yes, I have noticed that the Zernike terms seem to be more sensitive to the integration fineness (or histories in MC contexts). This relates to the statistical vs. truncation error of FETs, in which the higher order harmonics resolve slower than the lower orders. In this particular FE case it is due to the quadrature resolution instead.

I have seen this same effect with the Legendre polynomials as well, but not as strongly. I attribute the Zernike sensitivity to its 2D nature. To me this means it requires around a power of 2 more data points to resolve than a similarly-ordered 1D series.

I've usually compensated by either increasing the mesh fineness (or particle count) or decreasing the max order. Uncertainty/error information can also be utilized in post-processing to identify poorly resolved coefficients and zero those out as necessary.

**Comment by lindsayad** [comment]
@BruceWyxv thanks for the feedback! It's definitely consistent with what I've been seing

**Comment by lindsayad** [comment]
I'm pretty sure I found the issue...I was mistakenly using a tally that had scores outside the Zernike domain. E.g. I defined a Zernike filter with radius 60 inside of a 120x120 square, so I was getting contributions to the tally in the corners of the square outside the circle. Once I changed the geometry to actually be cylindrical, the oscillatory issues disappeared.

![image](https://user-images.githubusercontent.com/10248304/40666971-32ec440e-631e-11e8-983f-d2642e64fc2a.png)
